help and verbose mode

diff --git a/chive b/chive
--- a/chive
+++ b/chive
@@ -2,30 +2,38 @@
 
 TMP=/tmp/chive.tmp
 
-while getopts ":u:i:" o; do
+usage() {
+  echo "usage: chive [-u user] [-i identity_file] [-h help] [-v verbose]" && exit 1
+}
+
+while getopts ":u:i:vh" o; do
   case $o in
     u) USER=$OPTARG;;
     i) ID=$OPTARG;;
+    v) v=true;;
+    h) h=true;;
     \?) echo "unknown option: -$OPTARG" >&2; exit 1;;
     :) echo "missing option argument for -$OPTARG" >&2; exit 1;;
-    *) echo "usage: chive [-u user] [-i identity_file]" && exit 1;;
   esac
 done
 
+[ $h ] && usage
 [ -z $USER ] && USER=$(whoami)
 [ -z $ID ] && ID=~/.ssh/id_rsa
+
 
 proc() {
   if ping -W 1 -c 1 hive$1.cs.berkeley.edu &>/dev/null; then
     data=$(ssh -oStrictHostKeyChecking=no -oPasswordAuthentication=no -i $2 $USER@hive$1.cs.berkeley.edu "users | wc -w" 2>/dev/null)
-    [[ $? -eq 0 ]] && printf "%2d %02d\n" "$1" "$data"
+    [[ $? -eq 0 ]] && printf "%02d  %02d\n" "$1" "$data"
   fi
 }
 
 export -f proc
-printf %d\\n {1..30} | xargs -n1 -P30 -I{} bash -c "proc {} $ID" > $TMP
-smol=$(sort -k2 $TMP | head -n1 | awk '{print $1}')
-[ -z $smol ] && echo "No hives available" && exit
+printf %d\\n {1..30} | xargs -n1 -P30 -I{} bash -c "proc {} $ID" | sort -k2 > $TMP
+smol=$(head -n1 $TMP | awk '{$1=$0+0;print $1}')
+[ -z $smol ] && printf "Unable to connect to any hives! Check your username and identity file.\n" && exit
+[ $v ] && printf "HIVE    USERS\n" && sed -e 's/^/hive/' $TMP
 rm -rf $TMP
 
 ssh -i $ID $USER@hive$smol.cs.berkeley.edu
